alias v=nvim
alias vi=nvim
alias cd=z
alias vconf="cd ~/.dotfiles/ && v"
alias b="brew install"
alias bc="brew install --cask"
alias bs="brew search"
alias sub="osdb get -l spa"
alias lds="diskutil list"
alias l="eza -l -g --icons --group-directories-first"
alias ll="l -a"
alias cl=clear
alias kssh="kitty +kitten ssh"
alias lg=lazygit
