gui:
  nerdFontsVersion: 3
  theme:
   defaultFgColor:
     - "#d8dee9"
   cherryPickedCommitFgColor:
     - "#88c0d0"
   cherryPickedCommitBgColor:
     - "#d8dee9"
   activeBorderColor:
     - "bold"
   unstagedChangesColor:
     - "#bf616a"
   selectedLineBgColor:
     - "#434c5e"
   searchingActiveBorderColor:
     - "bold"
   optionsTextColor:
     - "#88c0d0"
   inactiveBorderColor:
     - "#4c566a"
git:
  parseEmoji: true
customCommands:
  - key: '<c-c>'
    context: 'global'
    command: "scope=\"{{.Form.Scope}}\"; if [ -z \"$scope\" ]; then git commit -m '{{.Form.Emoji}} {{.Form.Description}}'; else git commit -m '{{.Form.Emoji}} ({{.Form.Scope}}): {{.Form.Description}}'; fi"
    prompts:
      - type: 'menuFromCommand'
        title: 'What kind of change is it?'
        key: 'Emoji'
        command: 'gitmoji -l'
        filter: '(?P<unicode>[^ -]+) - (?P<emoji>[^ -]+) - (?P<type>.+)'
        valueFormat: '{{ .unicode }}'
        labelFormat: '{{ .unicode }} {{ .type }}'
      - type: 'input'
        title: 'Description of the change'
        key: 'Description'
        initialValue: ''
      - type: 'input'
        title: 'Scope (optional)'
        key: 'Scope'
        initialValue: ''
