gui:
  nerdFontsVersion: 3
  theme:
   defaultFgColor:
     - "#d8dee9"
   cherryPickedCommitFgColor:
     - "#88c0d0"
   cherryPickedCommitBgColor:
     - "#d8dee9"
   activeBorderColor:
     - "bold"
   unstagedChangesColor:
     - "#bf616a"
   selectedLineBgColor:
     - "#434c5e"
   searchingActiveBorderColor:
     - "bold"
   optionsTextColor:
     - "#88c0d0"
   inactiveBorderColor:
     - "#4c566a"
git:
  parseEmoji: true
customCommands:
  - key: '<c-c>'
    context: 'global'
    command: "~/.local/bin/scripts/commit-message-with-gitmoji.sh \"{{.Form.Emoji}}\" \"{{.Form.Scope}}\" \"{{.Form.Description}}\""
    prompts:
      - type: 'menuFromCommand'
        title: 'What kind of change is it?'
        key: 'Emoji'
        command: 'gitmoji -l'
        filter: '(?P<unicode>[^ -]+) - (?P<emoji>[^ -]+) - (?P<type>.+)'
        valueFormat: '{{ .emoji }}'
        labelFormat: '{{ .unicode }} {{ .type }}'
      - type: 'input'
        title: 'Description of the change'
        key: 'Description'
        initialValue: ''
      - type: 'input'
        title: 'Scope (optional)'
        key: 'Scope'
        initialValue: ''
  - key: '<c-x>'
    context: 'global'
    command: "~/.local/bin/scripts/commit-message-with-gitmoji.sh \"{{.Form.Emoji}}\" \"{{.Form.Scope}}\" \"{{.Form.Description}}\""
    prompts:
    - type: 'input'
      title: 'What kind of change is it?'
      key: 'Emoji'
      suggestions:
        command: "gitmoji -l"
    - type: 'input'
      title: 'Description of the change'
      key: 'Description'
      initialValue: ''
    - type: 'input'
      title: 'Scope (optional)'
      key: 'Scope'
      initialValue: ''
  - key: '<c-z>'
    context: 'global'
    command: "~/.local/bin/scripts/commit-message-with-gitmoji-and-branch-name.sh \"{{.Form.Emoji}}\" \"{{.Form.Description}}\""
    prompts:
    - type: 'input'
      title: 'What kind of change is it?'
      key: 'Emoji'
      suggestions:
        command: "gitmoji -l"
    - type: 'input'
      title: 'Description of the change'
      key: 'Description'
      initialValue: ''
services:
  gh_personal: 'github:github.com'
  gh_nuvo: 'github:github.com'
