"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[directory]
style = 'cyan'

[character]
success_symbol = ' [➜](bold green)'
error_symbol = ' [➜](bold red)'
vimcmd_symbol = ' [N](bold green)'
vimcmd_replace_one_symbol = ' [R](bold purple)'
vimcmd_replace_symbol = ' [R](bold purple)'
vimcmd_visual_symbol = ' [V](bold yellow)'

[package]
disabled = false
symbol = '󰓹 '
style = 'blue'

[time]
disabled = false
format = '[✦](cyan) at [$time]($style)'
style = 'yellow'
time_format = '%T'
utc_time_offset = '-5'

[git_branch]
symbol = ' '
truncation_symbol = ''
style = '#D08770'

[git_status]
format = '([\[$conflicted$deleted$renamed$modified$typechanged$staged$untracked\]]($style) )'

[java]
symbol = '  '
style = 'red'

[gradle]
symbol = ' '
style = 'green'
